### ISSUE TITLE
Preview deployments broken (likely `@sveltejs/adapter-cloudflare@5.0.0` related)

### ISSUE THREAD

**Issue by techniq** [AdrianGonz97/cf-pages-action#26]
[LayerChart](https://github.com/techniq/layerchart/actions/workflows/deploy-preview.yml) preview deployments started failing yesterday (and [Svelte UX](https://github.com/techniq/svelte-ux/actions/workflows/deploy-preview.yml?page=2) 2 weeks ago) with `Could not resolve "../output/server/index.js"` (and other path) errors.

I believe it is attributed to updating `@sveltejs/adapter-cloudflare` to [5.0.0](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fadapter-cloudflare%405.0.0) or possibly the latest `wrangler` (`3.95.0` => `3.105.1`), but I'm having trouble confirming or identifying a solution.  I thought maybe needing to change `directory` [setting](https://github.com/AdrianGonz97/refined-cf-pages-action?tab=readme-ov-file#usage) but I couldn't find any details on what it should change to.  Also, the [production deployments](https://github.com/techniq/layerchart/actions/workflows/deploy-prod.yml) have been working.

<details>
<summary>Click for details</summary>

![Image](https://github.com/user-attachments/assets/bd09ca4b-8060-4315-8944-d7eb34e060a1)

![Image](https://github.com/user-attachments/assets/573db758-2fdd-41d5-b65f-9b17b7582805)

```
✘ [ERROR] Build failed with 2 errors:

  ✘ [ERROR] Could not resolve "../output/server/index.js"
  
      _worker.js:2:23:
        2 │ import { Server } from "../output/server/index.js";
          ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  
  ✘ [ERROR] Could not resolve "../cloudflare-tmp/manifest.js"
  
      _worker.js:3:49:
        3 │ ...est, prerendered, base_path } from "../cloudflare-tmp/manifest.js";
          ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  


✘ [ERROR] Build failed with 2 errors:

  ✘ [ERROR] Could not resolve "../output/server/index.js"
  
      _worker.js:2:23:
        2 │ import { Server } from "../output/server/index.js";
          ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  
  ✘ [ERROR] Could not resolve "../cloudflare-tmp/manifest.js"
  
      _worker.js:3:49:
        3 │ ...est, prerendered, base_path } from "../cloudflare-tmp/manifest.js";
          ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ```
</details>

Any thoughts on what might have changed and how to fix?  Thanks!

**Comment by techniq** [comment]
@AdrianGonz97 The issue is definitely related to no longer running the esbuild step in [@sveltejs/adapter-cloudflare@5.0.0](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fadapter-cloudflare%405.0.0).

To fix the `Could not resolve "../output/server/index.js"` and similar errors, I refined `build-preview.yml` to include `output` and `cloudflare-tmp` in the uploaded artifact.

```yml
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-build
          path: |
            packages/layerchart/.svelte-kit/cloudflare
            packages/layerchart/.svelte-kit/cloudflare-tmp
            packages/layerchart/.svelte-kit/output
```

and then updated `deploy-preview.yml` to include `/cloudflare` directory

```yml
            - name: Deploy to Cloudflare Pages
              uses: AdrianGonz97/refined-cf-pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  projectName: layerchart
                  deploymentName: Preview
                  directory: ${{ steps.preview-build-artifact.outputs.download-path }}/cloudflare
```

While this solved the `../output/server/index.js` and `../cloudflare-tmp/manifest.js` import issues, I'm now unable to resolve any of the NPM dependencies (such as `d3-shape`, `d3-scale`, `@layerstack/utils`, etc).  

![Image](https://github.com/user-attachments/assets/90e320c0-c918-4aa1-ad8c-a4b66524b6c7)

Based on the [PR](https://github.com/sveltejs/kit/pull/13132) it looks like this should be handled by wranger.

> This PR removes the esbuild step from the Cloudflare adapter since Wrangler now bundles the worker for us when deploying from the Cloudflare dashboard or via the Wrangler CLI. https://github.com/sveltejs/kit/pull/13072#issuecomment-2509025602

For now I'm going to downgrade to `@sveltejs/adapter-cloudflare@4.9.0` as I haven't had a PR preview in a few weeks.
