### ISSUE TITLE
Preview workflows with dependabot

### ISSUE THREAD

**Issue by tembbo** [AdrianGonz97/cf-pages-action#27]
I have my current preview workflow set up like this:

```yaml
name: Preview

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Deploy
              uses: AdrianGonz97/refined-cf-pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  projectName: portfolio
                  directory: .svelte-kit/cloudflare
                  deploymentName: Preview
```

I've also currently configured dependabot to auto-update dependencies. All my actions secrets are also transferred to dependabot secrets as well. But when dependabot triggers and action and creates a PR which triggers the preview workflow, I'm left with this error:

```sh
Error: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment
/home/runner/work/_actions/AdrianGonz97/refined-cf-pages-action/v1/dist/index.js:24394
        runId: import_github5.context.payload.workflow_run.id ?? import_github5.context.runId
                                                           ^

TypeError: Cannot read properties of undefined (reading 'id')
    at /home/runner/work/_actions/AdrianGonz97/refined-cf-pages-action/v1/dist/index.js:[24](https://github.com/realguse/portfolio/actions/runs/13018245891/job/36313605399?pr=36#step:6:25)394:60
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Does anyone know how to fix it, I've tried adding both the `pull-requests: write` and `issues: write` permissions to the workflow, but they don't seem to work.

Thanks!
