### ISSUE TITLE
Assumption made about deployment api result correlating to this action run

### ISSUE THREAD

**Issue by airtonix** [AdrianGonz97/cf-pages-action#30]
i see that you're printing the deployment urls to the PR.

But i was interested to see how you're doing it, and I see that you 

1. run the wrangler command
2. make an api request to cloudflare to list the deployments
3. assume the last deployment is the one we just did in `2`.

In a high activity repo, I'm not sure this would guarantee accurate results.

I've found that a more accurate way is to parse the output of the deploy command and assume the urls returned by the command are in fact the ones that we just created. 

<details><summary><code>.github/tools/helpers.sh</code></summary>
<p>

```sh
#!/usr/bin/env bash

requires_command() {
    local command
    local message

    command=$1
    message=$2

    if ! command -v "$command" &>/dev/null; then
        echo "$message"
        exit 1
    fi
}

requires_arg() {
    local arg
    local message

    arg=$1
    message=$2

    if [[ -z $arg ]]; then
        echo "$message"
        exit 1
    fi

}

arg_or_prompt() {
    local message
    local value
    local output

    message="${1}"
    value="${2}"
    output=""

    if [ -z "${value}" ]; then
        read -r -p "$message: " output
        echo "${output}"
    else
        echo "$value"
    fi
}

match_first() {
    local pattern
    local group

    pattern=$1
    group=$2
    # split string by newline
    IFS=$'\n' read -rd '' -a lines <<<"$3"
    for line in "${lines[@]}"; do
        # echo "[TEST] $line"
        if [[ $line =~ $pattern ]]; then
            echo "${BASH_REMATCH[$group]}"
            break
        fi
    done
}



# remove first blank line and any leading whitespace
dedent() {
    local text="${1}"
    local output

    output=$(echo "${text}" | sed 's/^[ \t]*//')
    output=$(echo "${output}" | sed '1d')

    echo "${output}"
}

# renders a jq template string with supplied object
template() {
    local template
    local object

    template=$1
    object=$2

    echo "$object" | jq -r -c "$template"
}
```

</p>
</details>

<details><summary><code>.github/tools/matchers.sh</code></summary>
<p>

```sh
#!/bin/bash

match_all() {
    local pattern

    pattern=$1
    # split string by newline

    IFS=$'\n' read -rd '' -a lines <<<"$2"
    output=$(jq -n "[]")

    for line in "${lines[@]}"; do
        # echo "[TEST] $line" >&3 # don't match if pattern is empty
        if [[ $line =~ $pattern ]]; then
            # Create a new object for each match
            item=$(jq -n "[]")
            # loop through matches but don't match the whole line
            for i in "${!BASH_REMATCH[@]}"; do
                # skip the first match which is the whole line
                if [[ $i -eq 0 ]]; then
                    continue
                fi

                # Get the key and value from the match
                value="${BASH_REMATCH[$i]}"

                # Add the key-value pair to the item object
                item=$(jq --arg value "$value" '. += [$value]' <<<"$item")
            done
            # Append the item to the output array
            output=$(jq --argjson item "$item" '. += [$item]' <<<"$output")
        fi
    done

    # Convert the output to a JSON array
    echo "$output" | jq -c '.'
}

```

</p>
</details> 

<details><summary><code>.github/tools/cloudflare-urls.sh</code></summary>
<p>

```sh
#!/usr/bin/env bash

HEREPATH=$(
    cd "$(dirname "${BASH_SOURCE[0]}")" || exit
    pwd
)

# shellcheck disable=SC1091
source "$HEREPATH"/matchers.sh || { echo "Failed to load matchers.sh"; exit 1; }
source "$HEREPATH"/helpers.sh || { echo "Failed to load helpers.sh"; exit 1; }

extract_deployment_urls() {
    local log_output

    log_output="$1"

    urls=$(match_all "(.+)\:deploy.+Deployment complete! Take a peek over at (https://.+)" "$log_output")
    alias_urls=$(match_all "(.+)\:deploy.+Deployment alias URL: (https://.+)" "$log_output")

    output=$(jq -s '
      .[0] as $real |
      .[1] as $alias |
      ($real + $alias) |
      group_by(.[0]) |
      map([{ name: (.[0][0]), url: .[0][1], alias: .[1][1] }]) |
      add' <<<"$urls $alias_urls")

    echo "$output" | jq . -c
}

requires_command jq "jq is required to parse the output"

# some subcommands that allow use to either:
# - extract the urls into json
# - extract the urls into github output format
# - extract the urls and print them to stdout

case "$1" in

json)
    extract_deployment_urls "$(cat)"
    ;;
github)
    input="$(cat)"
    output=$(extract_deployment_urls "$input" | jq "@json")
    echo "$input"
    echo "${2:-Urls}=$output" >>"$GITHUB_OUTPUT"
    ;;
esac
```

</p>
</details>

Then in your action step: 

```yml

      - name: Deploy to Preview
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_BRANCH: ${{ github.head_ref }}
        run: |
          moon run :deploy --affected --remote |
            ./.github/tools/cloudflare-urls.sh github FooBarBaz

      - name: SuccessMessage
        id: message
        if: success() && steps.deploy.outputs.Urls != ''
        run: |
          echo ${{ steps.deploy.outputs.FooBarBaz }}

```
