### ISSUE TITLE
docs: Add instructions on how to add GH Deployments from forked PRs

### ISSUE THREAD

**Issue by zernonia** [AdrianGonz97/cf-pages-action#9]
same issue as the official plugin, it's missing `apiToken` because in forked repo it doesn't have access to the secret.
I was expecting this action to work because it mentioned `✅ GitHub Deployments on PRs from forks` on readme.

 
![image](https://github.com/AdrianGonz97/refined-cf-pages-action/assets/59365435/a7fbe5ac-0a06-4d5b-8db4-7f2517c2fee2)

<details><summary>relevant workfile</summary>
<p>

```bash
name: Publish www

on:
  push:
    branches:
      - dev
    paths:
      - 'apps/www/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'apps/www/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build www
        run: pnpm build

      # Run a action to publish docs
      - name: Publish to Cloudflare Pages
        uses: AdrianGonz97/refined-cf-pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: shadcn-vue
          directory: .vitepress/dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          # branch: main
          # Optional: Change the working directory
          workingDirectory: apps/www
          wranglerVersion: '3'
```

</p>
</details>

**Comment by AdrianGonz97** [comment]
Hey @zernonia, thanks for raising an issue! Sorry for the delay, I hadn't realized that notifications weren't enabled on this repo. That should be fixed now.

The action does support GitHub Deployments from PR forks, however, it's not (yet) documented as to how to get that particular feature working.

Here's an example workflow of how we do it in Melt UI: https://github.com/melt-ui/melt-ui/blob/develop/.github/workflows/preview.yml

The reason as to why it's not documented yet is because it requires the use of the [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event in the action, which has security concerns that need to be considered before plopping it into a repo. I'm still trying to find the best way to document this clearly without encouraging people to unknowingly expose secrets during preview deployments. 

However, if your site does not use/have any secrets during **the build step** or in your **preview environment on CF**, then it should be alright to use. If you're using it for `shadcn-vue`, which looks to be just a static site without needing any secrets, then it's probably a good fit. 

Here's an example of this:
<details><summary>Preview Deployment with NO SECRETS</summary>
<p>

```yaml
name: Preview Deployment
on:
  pull_request_target:
    paths:
      - "apps/www/**"

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    name: Deploy www Preview to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # Run a build step here
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      # PNPM Store cache setup
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Deploy to Cloudflare Pages
        uses: AdrianGonz97/refined-cf-pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_API_TOKEN_ACCOUNT_ID }}
          projectName: shadcn-vue
          directory: .vitepress/dist
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/www
          deploymentName: Preview
          wranglerVersion: "3"
```

</p>
</details>


In cases that it _does use secrets_, then the deployment job can be fitted with an `environment` field that requires manual approval before each deployment (like it does in the Melt UI workflow).

Manual approval needs to be setup at the repo level, as described in this PR under the "Make the `Preview` environment protected" step: https://github.com/melt-ui/melt-ui/pull/899

<details><summary>Preview Deployment WITH SECRETS</summary>
<p>

```yaml
name: Preview Deployment
on:
  pull_request_target:
    paths:
      - "apps/www/**"

jobs:
  deploy-preview:
    environment: Preview # Requires manual approval before each deployment!
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    name: Deploy www Preview to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # Run a build step here
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      # PNPM Store cache setup
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build site
        run: pnpm build
        env:
          SOME_SECRET: "foo" # Uses some secret during build!

      - name: Deploy to Cloudflare Pages
        uses: AdrianGonz97/refined-cf-pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_API_TOKEN_ACCOUNT_ID }}
          projectName: shadcn-vue
          directory: .vitepress/dist
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/www
          deploymentName: Preview
          wranglerVersion: "3"
```
</p>
</details>

Hope this helps!
